### ISSUE TITLE
Scrollable suggestions list

### ISSUE THREAD

**Issue by pdc** [moroshko/react-autosuggest#148] opened 2016-04-14 15:37 UTC
My customer would like to have the list of suggestions show a scrollbar rather than have the suggestions container extend beyond the bottom of the viewpoint. It is possible to make something that looks the part by setting `max-height` and `overflow-y` properties on the suggestions-container element. There are two main problems

- selecting a suggestion using the arrow keys does not scroll the list to show the focussed suggestion;
- clicking on the scrollbar collapses the suggestions list on IE.

Is there an easy way to achieve this? Or do I need to dive in to modifying the `Autowhatever` component?

**Comment by cellog** [comment] 2016-04-15 19:34
this seems related to #133 

The problem is that when you interact with the suggestions list, it removes focus from the input, which closes the suggestions list.  I think the blur() needs to be a bit more sophisticated.  It should close the list ONLY when a user interacts with an element outside the entire component, not just when the input is blurred

**Comment by moroshko** [comment] 2016-05-07 13:04
I believe that [this](https://github.com/moroshko/react-autowhatever/pull/6) and [this](https://github.com/moroshko/react-autosuggest/pull/153) will address this issue, so closing this one.

**Closed by moroshko** 2016-05-07 13:04 UTC
Labels: feature request
