### ISSUE TITLE
function onSuggestionsUpdateRequested({ value, reason }) reason not working?

### ISSUE THREAD

**Issue by philmetzger** [moroshko/react-autosuggest#189] opened 2016-06-14 10:23 UTC
The `reason` param of the function `onSuggestionsUpdateRequested` only seems to display `'type'`. `'blur'` for example does not seem to happen. Any fixes for this?

**Comment by lropero** [comment] 2016-06-21 07:22
This is happening to me as well. Only 'type' or 'click' seems to be working.

**Comment by moroshko** [comment] 2016-07-21 09:08
[Here](http://codepen.io/moroshko/pen/jAzGBL?editors=0010) is an example of `reason === 'blur'`:

To reproduce:

1. Type 'c'
2. Press Up
3. Click outside of the Autosuggest

Could you provide the steps to reproduce the issue you're seeing?

**Comment by jehrlich** [comment] 2016-07-21 21:32
I suspect the issue is that `onSuggestionsUpdateRequested` is not called if you leave an Autosuggest by clicking another element. I suppose this makes sense. I need a way to detect an Autosuggest losing focus in any way, because I use multiple Autosuggest components that share state for updating suggestions. Issue #20 may relate ...

**Comment by moroshko** [comment] 2016-07-21 22:00
@jehrlich I still can't clearly understand what is the problem you are experiencing. I'm closing this issue for now. If you are still struggling, please create a new issue with a runnable example and steps to reproduce.

**Closed by moroshko** 2016-07-21 22:00 UTC
