### ISSUE TITLE
Suggestion bar opens again after initial selection. Duplicate open. 

### ISSUE THREAD

**Issue by RefX32** [moroshko/react-autosuggest#573] opened 2018-09-13 17:41 UTC
**Steps to reproduce**: 
1. Go on the homepage: https://react-autosuggest.js.org/
2. on Basic, textbox, type 'c', select 'C#'
3. Click anywhere on the screen (I clicked the bottom textbox on "multiple sections")
4. Notice, how the "basic textbox" was selected again and auto-fill popped up. 

**Expected behavior**: Once we select something from the autofill, clicking anywhere else on the screen should NOT popup another autofill suggesting the same thing we just picked on the previously selected textbox.

**Comment by moroshko** [comment] 2018-09-13 22:54
Duplicate of #568

**Closed by moroshko** 2018-09-13 22:54 UTC
