### ISSUE TITLE
Bug With Controlled Component Implementation

### ISSUE THREAD

**Issue by pathsny** [moroshko/react-autosuggest#53] opened 2015-07-29 02:51 UTC
Controlled Components allow you to set value, however this effectively conflates two different concerns.
Setting the currently selected value should be equivalent to changing the selection the user has made.
Setting the currently selected inputValue should be equivalent to the user entering new text.

Currently setting value does not update the suggestion list. 

What I'm really looking for is a way to simply reset the component between submissions, but there is no easy way to do this. Using the Controlled Component approach results in subtle bugs where the previous options are still displayed even when the input is blank.

Ideally I would like to either implement a "reset" functionality as an uncontrolled component or to switch the way "value" is treated as a prop and actually make it trigger a fresh search for options (or optionally to  replace the value prop with 2 props. inputValue and selectedValue.

**Comment by idolize** [comment] 2015-07-29 20:52
This is being addressed in the v2 branch

**Comment by pathsny** [comment] 2015-07-29 23:27
@idolize  This IS a bug report about the v2 branch, is it opened in the wrong area?

**Comment by idolize** [comment] 2015-07-30 00:13
@pathsny Sorry, I didn't realize you were referring to the `2.0` branch. To clarify: the issue is that you can't set an "empty" selected suggestion via `value`?

It looks like that should be possible in the code, as long as your parent component (the one controlling the `Autosuggest`) doesn't rely purely on using `onSuggestionSelected` to maintain the value in it's state, because right now that callback will not be triggered unless an actual suggestion is selected.

Perhaps a workaround would be adding an empty string to your suggestions array? Or using `onChange` instead of `onSuggestionSelected` to maintain the value...

**Comment by pathsny** [comment] 2015-07-30 00:33
@idolize the issue is that even when the value is set to empty string, the list of suggestions does not update (ideally to an empty list). The problem is that "value" could be referring either to the value in the textbox as a user had typed it, or it could be referring to the selected value when the user highlights a specific option from pre-selected text.

I was proposing two different props. One to represent inputValue. When the prop changes, the function to fetch suggestions should be executed again. The other is selectedValue. When the prop changes, the only change should be to change the highlighted suggestion. The former "inputValue" prop is what I'm looking for.

The whole reason I'm doing this is because right now there is no way to reset the component state to a completely fresh state. I also propose that a "reset" function would be very useful when this component is used as an uncontrolled component

**Comment by sconno05** [comment] 2015-09-03 19:54
I ran into this issue too (I need the ability to prepopulate the input field in a form).  Any idea when v2 will be ready?  I'm happy to help if needed.

**Comment by moroshko** [comment] 2015-09-19 05:40
Sorry guys it took me so long to get back to this. I just released 2.0 which supports controlled components. However, I'm not sure that it solves the issue that @pathsny describes.

In a controlled component, I see `value` to simply be input's value. It has nothing to do with the selected suggestion.

@pathsny Do you basically expect the suggestions function to be called when `value` changes?

**Comment by pathsny** [comment] 2015-09-20 01:06
Hi Misha, that's correct. I expect the suggestions function to be called
when the value changes. The easiest way to see the issue is when you set
the value to blank string. When the focus is on the input you get a popup
of suggestions even though the string is blank.

**Comment by moroshko** [comment] 2015-09-21 09:56
Hey Vishnu, Do you expect the suggestions list to close when the value is updated to  empty string and the input is focused? I created a small demo [here](http://jsbin.com/kineromico/1/edit?html,js,output). Could you please modify it to highlight the issue?

**Comment by pathsny** [comment] 2015-09-22 22:27
yep, will do today thanks. My underlying thesis is that setting the value
of the text field should result in the suggestions list updating (and
potentially becoming empty for an empty string for example). One option
would be to move the value field from the top level component to the
textfield so that it's clear that it represents the value of the text field
and not the selected value.

**Comment by pathsny** [comment] 2015-09-23 06:08
Hi Misha, your demo is actually perfect to demonstrate the issue. When the
text changes to 'n' I would expect the suggestions list to be "nunawading"
but the suggestions list still starts with 'm'.  Is there a reason you do
not believe that is appropriate?

**Comment by moroshko** [comment] 2015-11-12 11:30
@pathsny Sorry for the late reply. What you suggest sounds more than reasonable! Mind creating a PR?

**Comment by moroshko** [comment] 2015-12-27 06:50
@pathsny This should be solved in 3.0. Check out [this example](http://codepen.io/moroshko/pen/obzQXd).

    npm install react-autosuggest@3.0-latest --save

**Closed by moroshko** 2015-12-27 06:50 UTC
