### ISSUE TITLE
redux.creatStore is not a function

### ISSUE THREAD

**Issue by craigcosmo** [moroshko/react-autosuggest#296] opened 2016-11-21 07:37 UTC
Hi,

I just install the latest version. Then copied the code from basic sample and make a component (compoent Auto) with that code. Then I import Auto into my project. Run, then I got this error

```
AutosuggestContainer.js:100Uncaught TypeError: (0 , _redux.createStore) is not a function(…)
```

Here is the code for Auto of component https://jsfiddle.net/craigcosmo/ju43d66a/

**Comment by moroshko** [comment] 2016-11-29 22:55
I can't see in the external resources that you import `react-autosuggest`.

[Here](http://codepen.io/moroshko/pen/LGNJMy) is a Basic Codepen example that you can start to play with.

Does this help?

**Comment by thebigredgeek** [comment] 2016-12-02 19:21
@moroshko why use redux internally?  Wouldn't it be better to allow the app itself to handle state rather than implicitly forcing a new redux store?  Seems kinda hacky :(

**Comment by thebigredgeek** [comment] 2016-12-02 19:22
I am also having this issue :(

**Comment by thebigredgeek** [comment] 2016-12-02 19:52
https://github.com/moroshko/react-autosuggest/issues/260

**Comment by superliuwr** [comment] 2016-12-07 02:36
I am having the same issue. Is there anyone figuring out how to get rid of this?

**Comment by moroshko** [comment] 2016-12-07 02:58
@superliuwr Could you help creating a minimal Codepen that reproduces the issue?

**Comment by superliuwr** [comment] 2016-12-07 03:28
@moroshko I tried putting just the component itself into a Codepen and it didn't reproduce the issue. It appears something to do with either Redux or my webpack config. There is a file named redux.js in your source code which I suspect causing name resolving issue of Redux. I however can not prove it at the moment.

**Comment by ztratar** [comment] 2016-12-09 02:30
It seems the error occurs when a redux store has already been instantiated, but then this library attempts to create another one. Babel/webpack parsing error perhaps?

**Comment by craigcosmo** [comment] 2016-12-09 05:12
@moroshko this is a simple demo that reproduces the bug

https://github.com/craigcosmo/demo

**Comment by adack123** [comment] 2016-12-28 16:47
I know I'm late to the party, but can anyone actually provide a solid example of the failings of this? I have autosuggest working flawlessly in a massive react-redux app. The above demo appears broken.

**Comment by craigcosmo** [comment] 2016-12-28 16:48
Hi, 

Example here https://github.com/craigcosmo/demo

**Comment by craigcosmo** [comment] 2016-12-28 16:58
@adack123 I updated the demo, fix the broken dependecies

**Comment by adack123** [comment] 2016-12-28 17:04
Hey @craigcosmo 

Sorry to be the bearer of bad news but I just tried out the demo and I'm still getting a lot of webpack related thrown errors revolving around sass and image files.

**Comment by craigcosmo** [comment] 2016-12-29 04:03
@adack123 I know why, the image was empty, therefore it was not pushed to git. But the build require the image folder so it complains. I made the fix. please have a look again

**Comment by craigcosmo** [comment] 2017-01-01 19:30
@adack123 have you tested out the reproduction repo I posted?

**Comment by moroshko** [comment] 2017-01-08 04:21
`redux` and `react-redux` dependencies were removed in [v8.0.0](https://github.com/moroshko/react-autosuggest/releases/tag/v8.0.0). 

Could you please upgrade and verify that the issue is gone?

**Comment by craigcosmo** [comment] 2017-01-11 03:58
updated to v8, I got this error

<img width="741" alt="screen shot 2017-01-11 at 10 50 53 am" src="https://cloud.githubusercontent.com/assets/538657/21835081/cebb1c70-d7ec-11e6-8d13-b414b0eee49c.png">


reproducing https://github.com/craigcosmo/demo

**Comment by moroshko** [comment] 2017-01-11 05:03
@craigcosmo You have to add:
```js
this.onChange = this.onChange.bind(this);
```
in your constructor, or alternatively, write `onChange` like this:
```js
onChange = (event, { newValue, method }) => {
  this.setState({
    value: newValue
  })
};
```

(do the same for `onSuggestionsFetchRequested` and `onSuggestionsClearRequested`)

**Closed** 2017-01-27 07:01 UTC
