### ISSUE TITLE
Suggestions list stuck open after dragging a suggestion outside of the autosuggest

### ISSUE THREAD

**Issue by imerkle** [moroshko/react-autosuggest#412] opened 2017-07-24 14:36 UTC
Issue from here: https://github.com/callemall/material-ui/issues/7526#

**Comment by moroshko** [comment] 2017-07-24 14:43
Having read callemall/material-ui#7526, it's not clear to me what the issue is.

Could you please list the steps to reproduce the issue?

cc @oliviertassinari

**Comment by oliviertassinari** [comment] 2017-07-24 14:45
Here is an example, I hope that helps:

![juil -24-2017 16-45-12](https://user-images.githubusercontent.com/3165635/28528953-850125de-708f-11e7-9204-5ad42368cf35.gif)

**Comment by moroshko** [comment] 2017-07-24 14:49
After you drag the suggestion, **the focus is no longer on the input.**
What exactly do you expect to happen when pressing <kbd>Up</kbd>/<kbd>Down</kbd> afterwards?

**Comment by oliviertassinari** [comment] 2017-07-24 14:52
@moroshko I don't think that the issue is with the keybinding, but rather with an opened suggestion list. Focusing and blurring it will no longer close it.

**Comment by mrmojica** [comment] 2017-07-27 00:54
I'm experiencing the same behavior after the click hold and mouse-out, where the suggestions will no longer close.  Did anyone figure out a work around?

**Comment by moroshko** [comment] 2017-07-28 11:22
Yep, it's a bug.

In case anyone would like to contribute a PR, here are the steps to reproduce it:
1. Visit http://react-autosuggest.js.org
2. Focus on the Basic example input
3. Type `c`
4. Drag one of the suggestions to the rest of the page

**Observed behavior:** The input loses focus, causing the suggestions to be stuck in a visible state (clicking outside of the autosuggest doesn't close the suggestions).

**Expected behavior:** The input keeps focus. Clicking outside of the autosuggest closes the suggestions. See [Google's autosuggest](https://google.com) as an example.

**Comment by scotta-koorong** [comment] 2017-07-31 02:53
1. The Mousedown handler is called and justSelectedSuggestion is set to true
2. Then the input is blurred by the browser because you've clicked/dragged on another element other than the input box (aria-activedescendant doesn't seem to be doing its job)
3. Even clicking the input box to try focus and unfocus it doesn't work because justSelectedSuggestion remains true and isn't set back to false except until you click a suggestion.

This code separates the blurring of the input box from the hiding of the container

``
if (!_this2.justSelectedSuggestion) {
    _this2.onBlur();
    _this2.onSuggestionsClearRequested();
}
``

I'm still trying to figure out a fix for this, but this is the cause I believe.

**Comment by minhsong** [comment] 2018-03-23 07:37
Have anyone fix this issues? could you share how to fix this issues?

**Closed** 2018-09-10 03:47 UTC
Labels: bug, help wanted

**Comment by svante-jonsson** [comment] 2024-04-03 13:04
Was this issue resolved? I am still experiencing this issue on version 10.1.11
