### ISSUE TITLE
Feature request: Write best suggestion without end of typing 

### ISSUE THREAD

**Issue by mikhail-riabokon** [moroshko/react-autosuggest#108] opened 2016-01-15 19:31 UTC
Thank you for this autosuggest package. It is really helped my with my current task. But I have one feature request which I would like to suggest. 
For example you have next list of values:
* Food
* Facebook
* Ford

User types ```F```: All thee field are shown and input field already filled in background and can looks like [this](https://jsfiddle.net/Ly4k9j4n/1/).
User type ```Fo```: Ford and Food are shown. And field also filled by best match from suggestions.
If user wants to chose already matched value form background, user should press right arrow.

It can be configurable via props and I can help with implementation if you see sense in this.

**Comment by moroshko** [comment] 2016-01-16 06:30
@mikhail-riabokon Thanks for the jsfiddle! This is a duplicate of #102. Please join the discussion there.

**Closed by moroshko** 2016-01-16 06:30 UTC
