### ISSUE TITLE
Scroll not working in IE-11

### ISSUE THREAD

**Issue by sophy-cat** [moroshko/react-autosuggest#190] opened 2016-06-16 18:01 UTC
In IE-11 when setting a max-height and overflow: auto, when selecting the scrollbar with the mouse to view the results the suggestions disappear and the input loses focus. 
Mouse wheel and keyboard arrows work fine. Firefox and Chrome are also ok.

**Comment by gainsboroughtech** [comment] 2016-07-08 01:53
Anyone close to having a fix for this?  I've been very happy with this autosuggest tool, but my client is pushing to use something else because of this bug.  I've been putting him off looking for a fix but haven't been able to figure it out.  This is my last ditch plea...  thanks

**Comment by ThibWeb** [comment] 2016-07-08 06:37
Could you provide an example where this happens? I can't reproduce it with my own code, but it might be due to what I've done in my fork (https://github.com/moroshko/react-autosuggest/pull/155).

**Comment by gainsboroughtech** [comment] 2016-07-08 13:44
Sample here:  https://accounts.workorder.es/sandbox

As stated in original issue, when selecting the scrollbar with the mouse to view the results the suggestions disappear and the input loses focus. 
Mouse wheel and keyboard arrows work fine. Firefox and Chrome are also ok.

thanks

**Comment by gainsboroughtech** [comment] 2016-07-08 14:13
I have shouldRenderSuggestions set to always return true.  In IE, if you select an item first, you can then click on the scrollbar and it works, though now hard to get rid of the suggestion box.  If nothing is selected, that's when it disappears.   Your fork may be working due to the changes where you bypass the shouldRenderSuggestions check.

**Comment by LuckUY** [comment] 2016-08-05 15:01
I got the latest version (including fork #155) but I still have the same issue on IE. 

@gainsboroughtech, were you able to solve this issue?

Thanks

**Comment by fedegar33** [comment] 2016-08-12 20:50
I´m having this issue too using 5.0.1 version in IE11. Any hints to fix this?

Thanks.

**Comment by moroshko** [comment] 2016-08-13 02:24
Just heads up that I plan to fix this bug some time next week.

**Closed** 2016-08-15 13:21 UTC
Labels: bug

**Comment by moroshko** [comment] 2016-08-15 13:25
This should be fixed now in [v5.0.2](https://github.com/moroshko/react-autosuggest/releases/tag/v5.0.2).

**Comment by Nareshd5057** [comment] 2020-09-10 10:40
still i am facing issue. when i used renderSuggestionsContainer scroll not working in IE 11. Please help me on this :)
