### ISSUE TITLE
Multiple sections demo bug

### ISSUE THREAD

**Issue by Mark-L6n** [moroshko/react-autosuggest#46] opened 2015-07-05 17:31 UTC
Very nice!
FYI, noticed in [Multiple sections demo](http://moroshko.github.io/react-autosuggest/#Multiple sections) that all relevant sections sometimes appear, and sometimes don't.
error:  type 'ha'  or 'ga' [1st-word matches disappear on 2nd letter]
ok:  type 'hi' or 'go'
[From what is seen, could be related to whether or not a 3rd word is available that matches]

**Comment by moroshko** [comment] 2015-07-07 11:07
@Mark-L6n For "ha" the dictionary has only second word matches. This is why only the second section appears. Same for "ga". This is the expected behaviour.

**Comment by Mark-L6n** [comment] 2015-07-07 17:39
But if you type just "h" or "g" by themselves you see lots of 1st-word matches for "ha" and "ga".

**Comment by moroshko** [comment] 2015-07-16 04:08
@Mark-L6n Sorry, you're right. This is happening because [suggestions are randomized](https://github.com/moroshko/react-autosuggest/blob/master/examples/src/MultipleSections/MultipleSections.js#L15) on every new letter. Feel free to submit a Pull Request to improve this.

**Comment by moroshko** [comment] 2016-01-05 12:26
@Mark-L6n I just released 3.0, which comes with a brand new website. I assume we can close this issue now.

http://react-autosuggest.js.org/

**Closed by moroshko** 2016-01-05 12:26 UTC
Labels: examples
