### ISSUE TITLE
onBlur focusedSuggestion becomes null on hover any suggestion 

### ISSUE THREAD

**Issue by alex-shamshurin** [moroshko/react-autosuggest#287] opened 2016-11-10 09:53 UTC
I use `focusFirstSuggestion = {true}` and it works well.
If user does not choose anything from dropdown list, the first rendered suggestion becomes a field value when user leaves the field (onBlur).
But, if user moves mouse around suggestion's list (but does not click on any value), the `focusedSuggestion` is set to `null` on blur. 
I want `focusedSuggestion` in `onBlur` callback to never become `null` if user did not select any value by click. How to achieve that?

**Comment by moroshko** [comment] 2016-11-11 06:12
I'm trying to reproduce the behaviour you are describing in [this Codepen](http://codepen.io/moroshko/pen/ObMQaE), but no luck.

> If user does not choose anything from dropdown list, the first rendered suggestion becomes a field value when user leaves the field (onBlur).

How do you blur the field? By clicking outside of the input? Pressing <kbd>Tab</kbd>? Something else? From what I can see, the value of the input doesn't change when the input is blurred.

Could you provide the exact steps to reproduce the unexpected behaviour?

**Comment by alex-shamshurin** [comment] 2016-11-11 08:32
When list is open, move mouse away from suggestion list but do not move mouse over suggestion list itself. In `onBlur` callback you will see that `focusedSuggestion ` is the first value. It's ok. But when your mouse pointer moves over suggestion list itself, `focusedSuggestion ` will be null in `onBlur`.

**Comment by moroshko** [comment] 2016-11-12 06:58
`focusedSuggestion` in `onBlur` callback is the suggestion that was highlighted just before the input element lost focus, **or null if there was no highlighted suggestion.**

When you have a highlighted suggestion, and then move the mouse away from the suggestions list, the highlighted suggestion disappears. There is no more highlighted suggestion, and this is why `focusedSuggestion` is `null` on blur. This is the expected behaviour.

**Comment by alex-shamshurin** [comment] 2016-11-12 08:10
In my case after `onBlur` event the field value cannot be null (if list in not empty). If no values are highlighted the first one must be `focusedSuggestion `.  I think I got it wrong, I should check the list itself and it's first value if `focusedSuggestion ` is null. I hoped that `focusFirstSuggestion = {true}` do the work and `focusedSuggestion ` will be always the highlighted value or first from the list, but anyway not `null`.

**Comment by moroshko** [comment] 2016-11-12 22:07
Sorry, I'm confused.

> In my case after onBlur event the field value cannot be null (if list in not empty).
I thought that we are talking about the `focusedSuggestion` argument being `null`, not the value of the input field?! As far as I'm aware, the input value doesn't change on blur.

**Comment by alex-shamshurin** [comment] 2016-11-14 08:13
No, I meant that business logic of my app (it's an autocomplete field)  does not allow the field to be empty. We are talking about `focusedSuggestion `, and I misundrestood that, I thought it acts like a selected value, but it is just a highlighted value.

**Comment by moroshko** [comment] 2016-11-14 14:57
react-autosuggest allows the input field to stay empty. I think react-select allows you to avoid empty value, so maybe have a look a it. Closing for now.

**Closed by moroshko** 2016-11-14 14:57 UTC

**Comment by angusfretwell** [comment] 2016-12-19 10:50
I seem to be experiencing the same thing. 

I have `focusFirstSuggestion`, and an `onBlur` handler which sets the `value` of the input to `focusedSuggestion`. If I blur by clicking above the input, it sets the `value` as expected, however when clicking below the input, `focusedSuggestion` comes through as null.

See http://codepen.io/anon/pen/jVdGbr

**Comment by moroshko** [comment] 2016-12-19 17:40
> however when clicking below the input, focusedSuggestion comes through as null.

@angusfretwell `focusedSuggestion` is `null` because **there is no focused suggestion** right before you click to blur.

Note, when you hover over from one suggestion to another, the focused suggestion changes. So, when the mouse leaves the last suggestion in the list, `focusedSuggestion` becomes `null`.

**Comment by angusfretwell** [comment] 2016-12-20 02:11
@moroshko Got it. I just got a bit confused since sometimes `focusedSuggestion` comes through as null when the `.suggestionFocused` class is applied to one of the suggestions.

My use case was similar to Alex's. I wanted the input value to be either one of the suggestions, or blank, so I ended up just setting the value to an empty string if `focusedSuggestion` is null.

Awesome library BTW 👍
